apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: xai-secret
  namespace: agentgateway-system
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: xai-secret
    creationPolicy: Owner
  data:
    - secretKey: Authorization
      remoteRef:
        key: llm-keys/xai
        property: Authorization
