apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: argocd
data:
  resource.customizations.health.gateway.networking.k8s.io_BackendTLSPolicy: |
    hs = {}
    if obj.status ~= nil and obj.status.ancestors ~= nil then
      for _, ancestor in ipairs(obj.status.ancestors) do
        if ancestor.conditions ~= nil then
          for _, condition in ipairs(ancestor.conditions) do
            if condition.type == "Accepted" and condition.status == "False" then
              hs.status = "Degraded"
              hs.message = condition.message
              return hs
            end
          end
        end
      end
      hs.status = "Healthy"
      hs.message = "Policy is accepted"
      return hs
    end
    hs.status = "Progressing"
    hs.message = "Waiting for controller to reconcile"
    return hs
