apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: agentgateway-control-plane
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  source:
    chart: enterprise-agentgateway
    repoURL: us-docker.pkg.dev/solo-public/enterprise-agentgateway/charts
    targetRevision: v2026.6.0
    helm:
      skipCrds: false
      parameters:
        - name: licensing.licenseKey
          value: eyJhZGRPbnMiOltdLCJleHAiOjE4MDE3NjE4MDUsImlhdCI6MTc2ODkyOTgwNSwiayI6InhmaVZxUSIsImx0IjoiZW50IiwicHJvZHVjdCI6ImFnZW50Z2F0ZXdheSJ9.pXPs0cMO6waOGdSkLqdJJxA9u0Ye2ojH4rtOdJAO8uI
          forceString: true
  destination:
    namespace: agentgateway-system
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
