apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kagent-enterprise-crds
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    chart: kagent-enterprise-crds
    repoURL: us-docker.pkg.dev/solo-public/kagent-enterprise-helm/charts
    targetRevision: 0.4.0
    helm:
      skipCrds: false
  destination:
    namespace: kagent
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
